<?php
/**
 * Font binary metadata reader and @font-face CSS generator
 *
 * Used by the font kit upload pipeline when a ZIP contains only font files
 * (e.g. a Google Fonts download) and no stylesheet: family name, weight and
 * style are read from the font binaries (name, OS/2, head and fvar tables)
 * and a stylesheet is generated so the existing CSS-parsing pipeline can run
 * unchanged.
 *
 * Supported binaries: TTF/OTF (sfnt) and WOFF (per-table zlib decompression).
 * WOFF2 requires Brotli, which PHP cannot provide — those files fall back to
 * filename-based detection and the caller is expected to surface a warning.
 *
 * Deliberately mirrors the style of the variable-fonts module's
 * Typost_Font_Parser: metadata-only parsing, graceful degradation (corrupt or
 * truncated files simply yield `false`), and no logging. The small sfnt
 * table-directory walk is duplicated from that parser on purpose — bundled
 * modules consume core's public API, never the other way around.
 *
 * The class is pure PHP (no WordPress function calls) so it can be unit
 * tested directly.
 *
 * @since 2.1.0
 */

if (!defined('ABSPATH')) {
    exit;
}

class Typost_Font_Metadata {

    /**
     * Per-table size ceiling (bytes). The tables we read (name, OS/2, head,
     * fvar) are all tiny; anything larger is treated as corrupt. Also serves
     * as the zip-bomb guard for WOFF decompression.
     */
    const MAX_TABLE_SIZE = 1048576;

    /**
     * Upper bound on table-directory entries we will walk.
     */
    const MAX_TABLES = 512;

    /**
     * Static weight-name suffixes recognised in filenames (lowercase).
     *
     * @var array
     */
    private static $filename_weights = array(
        'thin'       => 100,
        'hairline'   => 100,
        'extralight' => 200,
        'ultralight' => 200,
        'light'      => 300,
        'regular'    => 400,
        'normal'     => 400,
        'book'       => 400,
        'medium'     => 500,
        'semibold'   => 600,
        'demibold'   => 600,
        'bold'       => 700,
        'extrabold'  => 800,
        'ultrabold'  => 800,
        'black'      => 900,
        'heavy'      => 900,
    );

    /**
     * Generate a stylesheet for a set of font files.
     *
     * Files that cannot be parsed (WOFF2, EOT, corrupt binaries) fall back to
     * filename-based detection; each fallback is reported as a warning token
     * so the caller can surface a translated "review the generated CSS"
     * notice. Warning shape: array('code' => string, 'file' => basename).
     *
     * @param array  $font_files    Absolute paths to font files.
     * @param string $kit_base_path Kit directory the stylesheet will live in.
     * @return array array('css' => string, 'warnings' => array). css is ''
     *               when no usable font files were provided.
     */
    public static function generate_stylesheet(array $font_files, $kit_base_path) {
        $entries = array();
        $warnings = array();

        foreach ($font_files as $file) {
            $meta = self::read_font_metadata($file);
            if ($meta === false) {
                $meta = self::metadata_from_filename($file);
                $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
                $warnings[] = array(
                    'code' => ($ext === 'woff2') ? 'woff2_filename_guess' : 'filename_guess',
                    'file' => basename($file),
                );
            }
            $entries[] = array('file' => $file, 'meta' => $meta);
        }

        $css = self::build_css($entries, $kit_base_path);
        if ($css === '') {
            return array('css' => '', 'warnings' => array());
        }

        $header = "/*\n * Generated by Typography Stylist.\n * The uploaded font kit contained no stylesheet, so this file was created\n * from the font files' metadata. Review the families, weights and styles\n * below and adjust if needed.\n */\n\n";

        return array('css' => $header . $css, 'warnings' => $warnings);
    }

    /**
     * Read family/weight/style metadata from a font binary.
     *
     * @param string $file_path Absolute path to a ttf/otf/woff file.
     * @return array|false array('family' => string,
     *                           'weight' => int|array('min' =>, 'max' =>),
     *                           'style' => 'normal'|'italic',
     *                           'is_variable' => bool,
     *                           'source' => 'binary'),
     *                     or false when the file cannot be parsed
     *                     (WOFF2/EOT/corrupt/unreadable).
     */
    public static function read_font_metadata($file_path) {
        if (!is_string($file_path) || $file_path === '' || !is_file($file_path)) {
            return false;
        }

        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen -- Binary metadata parsing needs byte-level fseek/fread; WP_Filesystem cannot seek.
        $fh = fopen($file_path, 'rb');
        if ($fh === false) {
            return false;
        }

        try {
            $magic = fread($fh, 4);
            if ($magic === false || strlen($magic) < 4) {
                return false;
            }

            if ($magic === 'wOF2') {
                // WOFF2 table data is Brotli-compressed; PHP has no Brotli.
                return false;
            }

            $is_woff = ($magic === 'wOFF');
            if (!$is_woff && !in_array($magic, array("\x00\x01\x00\x00", 'OTTO', 'true'), true)) {
                return false;
            }

            rewind($fh);
            $tables = $is_woff ? self::read_woff_table_directory($fh) : self::read_sfnt_table_directory($fh);
            if (empty($tables) || !isset($tables['name'])) {
                return false;
            }

            $name_bytes = self::get_table_bytes($fh, $tables['name'], $is_woff);
            if ($name_bytes === false) {
                return false;
            }

            $names = self::parse_name_table($name_bytes);
            $family = '';
            if (isset($names[16])) {
                $family = $names[16];
            } elseif (isset($names[1])) {
                $family = $names[1];
            }
            if ($family === '') {
                return false;
            }

            $os2 = null;
            if (isset($tables['OS/2'])) {
                $os2_bytes = self::get_table_bytes($fh, $tables['OS/2'], $is_woff);
                if ($os2_bytes !== false) {
                    $os2 = self::parse_os2_table($os2_bytes);
                }
            }

            $is_variable = false;
            $wght = null;
            if (isset($tables['fvar'])) {
                $fvar_bytes = self::get_table_bytes($fh, $tables['fvar'], $is_woff);
                if ($fvar_bytes !== false && strlen($fvar_bytes) >= 12) {
                    $fvar_header = unpack('nmajorVersion', substr($fvar_bytes, 0, 2));
                    if ($fvar_header !== false && $fvar_header['majorVersion'] === 1) {
                        $is_variable = true;
                        $wght = self::parse_fvar_wght($fvar_bytes);
                    }
                }
            }

            $style = 'normal';
            if ($os2 !== null && $os2['italic'] !== null) {
                $style = $os2['italic'] ? 'italic' : 'normal';
            } else {
                $mac_italic = null;
                if (isset($tables['head'])) {
                    $head_bytes = self::get_table_bytes($fh, $tables['head'], $is_woff);
                    if ($head_bytes !== false) {
                        $mac_italic = self::parse_head_mac_style($head_bytes);
                    }
                }
                if ($mac_italic !== null) {
                    $style = $mac_italic ? 'italic' : 'normal';
                } else {
                    $subfamily = '';
                    if (isset($names[17])) {
                        $subfamily = $names[17];
                    } elseif (isset($names[2])) {
                        $subfamily = $names[2];
                    }
                    if ($subfamily !== '' && preg_match('/italic|oblique/i', $subfamily)) {
                        $style = 'italic';
                    }
                }
            }

            if ($wght !== null) {
                $weight = array('min' => $wght['min'], 'max' => $wght['max']);
            } elseif ($os2 !== null) {
                $weight = $os2['weight'];
            } else {
                $weight = 400;
            }

            return array(
                'family'      => $family,
                'weight'      => $weight,
                'style'       => $style,
                'is_variable' => $is_variable,
                'source'      => 'binary',
            );
        } finally {
            fclose($fh); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose -- Pairs with the fopen above.
        }
    }

    /**
     * Guess family/weight/style from a font filename.
     *
     * Understands the Google Fonts naming conventions:
     * `Family[wght].ttf`, `Family-Italic[wdth,wght].ttf` (variable) and
     * `Family-SemiBoldItalic.ttf` (static). Never fails — worst case the
     * whole basename becomes the family at weight 400. Callers should treat
     * the result as a guess and warn the user.
     *
     * @param string $file_path Path or bare filename.
     * @return array Same shape as read_font_metadata(), source 'filename'.
     */
    public static function metadata_from_filename($file_path) {
        $base = pathinfo($file_path, PATHINFO_FILENAME);

        // Variable pattern: Family[axes] / Family-Italic[axes]
        if (preg_match('/^(?P<fam>.+?)(?P<ital>-Italic)?\[(?P<axes>[^\]]*)\]$/i', $base, $m)) {
            $has_wght = (stripos($m['axes'], 'wght') !== false);
            return array(
                'family'      => self::clean_filename_family($m['fam']),
                // The real range is unknowable without parsing; 100–900 is the
                // conservative Google Fonts default. Callers warn about this.
                'weight'      => $has_wght ? array('min' => 100, 'max' => 900) : 400,
                'style'       => !empty($m['ital']) ? 'italic' : 'normal',
                'is_variable' => true,
                'source'      => 'filename',
            );
        }

        // Static pattern: Family-WeightName / Family-WeightNameItalic / Family-Italic
        if (preg_match('/^(?P<fam>.+)-(?P<suffix>[A-Za-z]+)$/', $base, $m)) {
            $suffix = strtolower($m['suffix']);
            $italic = false;
            foreach (array('italic', 'oblique') as $slant) {
                $len = strlen($slant);
                if (substr($suffix, -$len) === $slant) {
                    $italic = true;
                    $suffix = substr($suffix, 0, -$len);
                    break;
                }
            }
            if ($suffix === '' || isset(self::$filename_weights[$suffix])) {
                return array(
                    'family'      => self::clean_filename_family($m['fam']),
                    'weight'      => ($suffix === '') ? 400 : self::$filename_weights[$suffix],
                    'style'       => $italic ? 'italic' : 'normal',
                    'is_variable' => false,
                    'source'      => 'filename',
                );
            }
        }

        return array(
            'family'      => self::clean_filename_family($base),
            'weight'      => 400,
            'style'       => 'normal',
            'is_variable' => false,
            'source'      => 'filename',
        );
    }

    /**
     * Build @font-face CSS for parsed font entries.
     *
     * Faces are grouped by family + weight + style; formats of the same face
     * are merged into one src list ordered woff2 > woff > ttf > otf > eot.
     * url() paths are relative to the kit directory with each segment
     * rawurlencoded — the pipeline's url regexes reject unencoded whitespace.
     *
     * @param array  $entries       Each: array('file' => abs path, 'meta' => metadata array).
     * @param string $kit_base_path Kit directory.
     * @return string CSS text, '' when nothing usable.
     */
    public static function build_css(array $entries, $kit_base_path) {
        $groups = array();

        foreach ($entries as $entry) {
            if (empty($entry['file']) || empty($entry['meta']) || !is_array($entry['meta'])) {
                continue;
            }
            $meta = $entry['meta'];
            $family = self::sanitize_family(isset($meta['family']) ? $meta['family'] : '');
            if ($family === '') {
                continue;
            }
            $weight_css = self::weight_to_css(isset($meta['weight']) ? $meta['weight'] : 400);
            $style = (isset($meta['style']) && $meta['style'] === 'italic') ? 'italic' : 'normal';
            $key = $family . '|' . $weight_css . '|' . $style;

            if (!isset($groups[$key])) {
                $groups[$key] = array(
                    'family'      => $family,
                    'weight'      => $weight_css,
                    'style'       => $style,
                    'is_variable' => false,
                    'files'       => array(),
                );
            }
            $groups[$key]['files'][] = $entry['file'];
            if (!empty($meta['is_variable'])) {
                $groups[$key]['is_variable'] = true;
            }
        }

        if (empty($groups)) {
            return '';
        }

        $format_priority = array('woff2' => 0, 'woff' => 1, 'ttf' => 2, 'otf' => 3, 'eot' => 4);
        $blocks = array();

        foreach ($groups as $group) {
            $files = $group['files'];
            usort($files, function ($a, $b) use ($format_priority) {
                $ext_a = strtolower(pathinfo($a, PATHINFO_EXTENSION));
                $ext_b = strtolower(pathinfo($b, PATHINFO_EXTENSION));
                $pa = isset($format_priority[$ext_a]) ? $format_priority[$ext_a] : 5;
                $pb = isset($format_priority[$ext_b]) ? $format_priority[$ext_b] : 5;
                if ($pa === $pb) {
                    return strcmp($a, $b);
                }
                return $pa - $pb;
            });

            $srcs = array();
            foreach ($files as $file) {
                $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
                $srcs[] = "url('" . self::relative_url($file, $kit_base_path) . "') format('" . self::format_string($ext, $group['is_variable']) . "')";
            }

            $blocks[] = "@font-face {\n"
                . '    font-family: "' . $group['family'] . "\";\n"
                . '    src: ' . implode(",\n        ", $srcs) . ";\n"
                . '    font-weight: ' . $group['weight'] . ";\n"
                . '    font-style: ' . $group['style'] . ";\n"
                . "    font-display: swap;\n"
                . '}';
        }

        return implode("\n\n", $blocks) . "\n";
    }

    // -----------------------------------------------------------------
    // Container parsing (sfnt / WOFF)
    // -----------------------------------------------------------------

    /**
     * Read an sfnt (TTF/OTF) table directory.
     *
     * Same walk as the variable-fonts module's Typost_Font_Parser — the
     * duplication is deliberate (core must not depend on module internals).
     *
     * @param resource $fh Open file handle positioned at offset 0.
     * @return array tag => array('offset' => int, 'length' => int); empty on failure.
     */
    private static function read_sfnt_table_directory($fh) {
        $header = fread($fh, 12);
        if ($header === false || strlen($header) < 12) {
            return array();
        }

        $num_tables = unpack('nnumTables', substr($header, 4, 2));
        if ($num_tables === false) {
            return array();
        }
        $count = $num_tables['numTables'];
        if ($count < 1 || $count > self::MAX_TABLES) {
            return array();
        }

        $directory = fread($fh, 16 * $count);
        if ($directory === false || strlen($directory) < 16 * $count) {
            return array();
        }

        $tables = array();
        for ($i = 0; $i < $count; $i++) {
            $record = substr($directory, $i * 16, 16);
            $tag = rtrim(substr($record, 0, 4));
            $fields = unpack('Noffset/Nlength', substr($record, 8, 8));
            if ($fields === false) {
                continue;
            }
            $tables[$tag] = array(
                'offset' => $fields['offset'],
                'length' => $fields['length'],
            );
        }

        return $tables;
    }

    /**
     * Read a WOFF (v1) table directory.
     *
     * @param resource $fh Open file handle positioned at offset 0.
     * @return array tag => array('offset', 'comp_length', 'orig_length'); empty on failure.
     */
    private static function read_woff_table_directory($fh) {
        $header = fread($fh, 44);
        if ($header === false || strlen($header) < 44 || substr($header, 0, 4) !== 'wOFF') {
            return array();
        }

        $num_tables = unpack('nnumTables', substr($header, 12, 2));
        if ($num_tables === false) {
            return array();
        }
        $count = $num_tables['numTables'];
        if ($count < 1 || $count > self::MAX_TABLES) {
            return array();
        }

        $directory = fread($fh, 20 * $count);
        if ($directory === false || strlen($directory) < 20 * $count) {
            return array();
        }

        $tables = array();
        for ($i = 0; $i < $count; $i++) {
            $record = substr($directory, $i * 20, 20);
            $tag = rtrim(substr($record, 0, 4));
            $fields = unpack('Noffset/NcompLength/NorigLength', substr($record, 4, 12));
            if ($fields === false) {
                continue;
            }
            $tables[$tag] = array(
                'offset'      => $fields['offset'],
                'comp_length' => $fields['compLength'],
                'orig_length' => $fields['origLength'],
            );
        }

        return $tables;
    }

    /**
     * Fetch a table's raw bytes, decompressing WOFF tables when needed.
     *
     * @param resource $fh      Open file handle.
     * @param array    $entry   Directory entry from the table-directory readers.
     * @param bool     $is_woff Whether the container is WOFF.
     * @return string|false Raw table bytes, or false on failure/oversize.
     */
    private static function get_table_bytes($fh, array $entry, $is_woff) {
        if ($is_woff) {
            $comp_length = $entry['comp_length'];
            $orig_length = $entry['orig_length'];
            if ($comp_length < 1 || $comp_length > self::MAX_TABLE_SIZE || $orig_length < 1 || $orig_length > self::MAX_TABLE_SIZE || $comp_length > $orig_length) {
                return false;
            }
            if (fseek($fh, $entry['offset']) !== 0) {
                return false;
            }
            $raw = fread($fh, $comp_length);
            if ($raw === false || strlen($raw) < $comp_length) {
                return false;
            }
            if ($comp_length === $orig_length) {
                return $raw; // Stored uncompressed per WOFF spec.
            }
            // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- Corrupt uploads are expected input; failure is handled via the false return, and the length cap guards decompression bombs.
            $bytes = @gzuncompress($raw, $orig_length);
            if ($bytes === false || strlen($bytes) !== $orig_length) {
                return false;
            }
            return $bytes;
        }

        $length = $entry['length'];
        if ($length < 1 || $length > self::MAX_TABLE_SIZE) {
            return false;
        }
        if (fseek($fh, $entry['offset']) !== 0) {
            return false;
        }
        $bytes = fread($fh, $length);
        if ($bytes === false || strlen($bytes) < $length) {
            return false;
        }
        return $bytes;
    }

    // -----------------------------------------------------------------
    // Table parsers (pure byte-string input)
    // -----------------------------------------------------------------

    /**
     * Parse a name table (we only need nameIDs 1, 2, 16, 17).
     *
     * Preference order per nameID: Windows (platform 3, Unicode encodings,
     * US English first) > Unicode platform 0 > Macintosh Roman.
     *
     * @param string $bytes Raw name table.
     * @return array nameID => UTF-8 string; empty array when unparseable.
     */
    private static function parse_name_table($bytes) {
        if (!is_string($bytes) || strlen($bytes) < 6) {
            return array();
        }

        $header = unpack('nformat/ncount/nstringOffset', substr($bytes, 0, 6));
        if ($header === false) {
            return array();
        }

        $wanted = array(1 => true, 2 => true, 16 => true, 17 => true);
        $best = array();
        $table_length = strlen($bytes);

        for ($i = 0; $i < $header['count']; $i++) {
            $record_offset = 6 + $i * 12;
            if ($record_offset + 12 > $table_length) {
                break;
            }
            $record = unpack(
                'nplatform/nencoding/nlanguage/nnameId/nlength/noffset',
                substr($bytes, $record_offset, 12)
            );
            if ($record === false || !isset($wanted[$record['nameId']])) {
                continue;
            }

            $string_start = $header['stringOffset'] + $record['offset'];
            if ($record['length'] < 1 || $string_start + $record['length'] > $table_length) {
                continue;
            }

            $score = 0;
            $is_utf16 = false;
            if ($record['platform'] === 3) {
                $is_utf16 = true;
                if ($record['encoding'] === 1 || $record['encoding'] === 10) {
                    $score = ($record['language'] === 0x0409) ? 100 : 90;
                } else {
                    $score = 50;
                }
            } elseif ($record['platform'] === 0) {
                $is_utf16 = true;
                $score = 80;
            } elseif ($record['platform'] === 1 && $record['encoding'] === 0) {
                $score = ($record['language'] === 0) ? 70 : 60;
            } else {
                continue;
            }

            $raw = substr($bytes, $string_start, $record['length']);
            $value = $is_utf16 ? self::utf16be_to_utf8($raw) : self::latin1_to_utf8($raw);
            $value = trim(preg_replace('/[\x00-\x1F\x7F]/', '', $value));
            if ($value === '') {
                continue;
            }

            $name_id = $record['nameId'];
            if (!isset($best[$name_id]) || $score > $best[$name_id]['score']) {
                $best[$name_id] = array('score' => $score, 'value' => $value);
            }
        }

        $names = array();
        foreach ($best as $name_id => $candidate) {
            $names[$name_id] = $candidate['value'];
        }
        return $names;
    }

    /**
     * Parse the OS/2 fields we need.
     *
     * @param string $bytes Raw OS/2 table.
     * @return array|null array('weight' => int, 'italic' => bool|null); null
     *                    when the table is too short to read usWeightClass.
     */
    private static function parse_os2_table($bytes) {
        if (!is_string($bytes) || strlen($bytes) < 6) {
            return null;
        }

        $weight_field = unpack('nusWeightClass', substr($bytes, 4, 2));
        if ($weight_field === false) {
            return null;
        }
        $weight = $weight_field['usWeightClass'];
        if ($weight < 1) {
            $weight = 400;
        } elseif ($weight > 1000) {
            $weight = 1000;
        }

        $italic = null;
        if (strlen($bytes) >= 64) {
            $selection_field = unpack('nfsSelection', substr($bytes, 62, 2));
            if ($selection_field !== false) {
                $italic = (bool) ($selection_field['fsSelection'] & 0x01);
            }
        }

        return array('weight' => $weight, 'italic' => $italic);
    }

    /**
     * Read the italic bit from a head table's macStyle field.
     *
     * @param string $bytes Raw head table.
     * @return bool|null Italic flag, or null when the table is too short.
     */
    private static function parse_head_mac_style($bytes) {
        if (!is_string($bytes) || strlen($bytes) < 46) {
            return null;
        }
        $fields = unpack('nmacStyle', substr($bytes, 44, 2));
        if ($fields === false) {
            return null;
        }
        return (bool) ($fields['macStyle'] & 0x02);
    }

    /**
     * Extract the wght axis range from an fvar table.
     *
     * @param string $bytes Raw fvar table.
     * @return array|null array('min' => float, 'max' => float, 'default' => float),
     *                    or null when there is no readable wght axis.
     */
    private static function parse_fvar_wght($bytes) {
        if (!is_string($bytes) || strlen($bytes) < 12) {
            return null;
        }

        $header = unpack(
            'nmajorVersion/nminorVersion/naxesArrayOffset/nreserved/naxisCount/naxisSize',
            substr($bytes, 0, 12)
        );
        if ($header === false || $header['majorVersion'] !== 1 || $header['axisSize'] < 20 || $header['axisCount'] < 1 || $header['axisCount'] > 64) {
            return null;
        }

        $table_length = strlen($bytes);
        for ($i = 0; $i < $header['axisCount']; $i++) {
            $offset = $header['axesArrayOffset'] + $i * $header['axisSize'];
            if ($offset + 16 > $table_length) {
                return null;
            }
            $tag = rtrim(substr($bytes, $offset, 4));
            if ($tag !== 'wght') {
                continue;
            }
            $values = unpack('Nmin/Ndefault/Nmax', substr($bytes, $offset + 4, 12));
            if ($values === false) {
                return null;
            }
            return array(
                'min'     => round(self::fixed_to_float($values['min']), 2),
                'max'     => round(self::fixed_to_float($values['max']), 2),
                'default' => round(self::fixed_to_float($values['default']), 2),
            );
        }

        return null;
    }

    // -----------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------

    /**
     * Convert an OpenType Fixed (16.16, big-endian unsigned) to float.
     * Twin of Typost_Font_Parser::fixed_to_float() — duplicated on purpose.
     *
     * @param int $uint32 Unsigned 32-bit value from unpack('N').
     * @return float
     */
    private static function fixed_to_float($uint32) {
        if ($uint32 >= 0x80000000) {
            $uint32 -= 4294967296;
        }
        return $uint32 / 65536;
    }

    /**
     * Decode a UTF-16BE byte string to UTF-8, with a manual BMP-only
     * fallback when mbstring is unavailable.
     *
     * @param string $bytes
     * @return string
     */
    private static function utf16be_to_utf8($bytes) {
        if (function_exists('mb_convert_encoding')) {
            $converted = mb_convert_encoding($bytes, 'UTF-8', 'UTF-16BE');
            return ($converted === false) ? '' : $converted;
        }

        $result = '';
        $units = unpack('n*', substr($bytes, 0, strlen($bytes) - (strlen($bytes) % 2)));
        if ($units === false) {
            return '';
        }
        foreach ($units as $code) {
            if ($code >= 0xD800 && $code <= 0xDFFF) {
                continue; // Skip surrogates in the fallback path.
            }
            if ($code < 0x80) {
                $result .= chr($code);
            } elseif ($code < 0x800) {
                $result .= chr(0xC0 | ($code >> 6)) . chr(0x80 | ($code & 0x3F));
            } else {
                $result .= chr(0xE0 | ($code >> 12)) . chr(0x80 | (($code >> 6) & 0x3F)) . chr(0x80 | ($code & 0x3F));
            }
        }
        return $result;
    }

    /**
     * Decode a Latin-1-ish (Mac Roman approximation) byte string to UTF-8.
     *
     * @param string $bytes
     * @return string
     */
    private static function latin1_to_utf8($bytes) {
        $result = '';
        $length = strlen($bytes);
        for ($i = 0; $i < $length; $i++) {
            $code = ord($bytes[$i]);
            if ($code < 0x80) {
                $result .= $bytes[$i];
            } else {
                $result .= chr(0xC0 | ($code >> 6)) . chr(0x80 | ($code & 0x3F));
            }
        }
        return $result;
    }

    /**
     * Turn a filename fragment into a readable family name:
     * separators become spaces and camelCase words are split.
     *
     * @param string $fragment
     * @return string
     */
    private static function clean_filename_family($fragment) {
        $family = str_replace(array('_', '-'), ' ', $fragment);
        $family = preg_replace('/(?<=[a-z0-9])(?=[A-Z])/', ' ', $family);
        $family = preg_replace('/\s+/', ' ', $family);
        return trim($family);
    }

    /**
     * Sanitize a family name for embedding in a double-quoted CSS string.
     *
     * @param string $family
     * @return string
     */
    private static function sanitize_family($family) {
        if (!is_string($family)) {
            return '';
        }
        $family = str_replace(array('"', '\\'), '', $family);
        $family = preg_replace('/[\x00-\x1F\x7F]/', '', $family);
        $family = preg_replace('/\s+/', ' ', $family);
        return trim($family);
    }

    /**
     * Format a weight value (int or min/max range) for the font-weight
     * declaration, clamped to CSS's 1–1000 range.
     *
     * @param int|float|array $weight
     * @return string
     */
    private static function weight_to_css($weight) {
        if (is_array($weight) && isset($weight['min'], $weight['max'])) {
            return self::format_weight_number($weight['min']) . ' ' . self::format_weight_number($weight['max']);
        }
        return self::format_weight_number($weight);
    }

    /**
     * Clamp and format a single weight number, trimming trailing zeros.
     *
     * @param int|float $value
     * @return string
     */
    private static function format_weight_number($value) {
        if (!is_numeric($value)) {
            return '400';
        }
        $value = (float) $value;
        if ($value < 1) {
            $value = 1;
        } elseif ($value > 1000) {
            $value = 1000;
        }
        if ((float) (int) $value === $value) {
            return (string) (int) $value;
        }
        return rtrim(rtrim(number_format($value, 2, '.', ''), '0'), '.');
    }

    /**
     * CSS format() identifier for a file extension.
     *
     * @param string $ext         Lowercase file extension.
     * @param bool   $is_variable Whether the face is a variable font.
     * @return string
     */
    private static function format_string($ext, $is_variable) {
        $formats = array(
            'ttf'   => 'truetype',
            'otf'   => 'opentype',
            'woff'  => 'woff',
            'woff2' => 'woff2',
            'eot'   => 'embedded-opentype',
        );
        $format = isset($formats[$ext]) ? $formats[$ext] : 'truetype';
        if ($is_variable && $ext !== 'eot') {
            $format .= '-variations';
        }
        return $format;
    }

    /**
     * Path of a font file relative to the kit directory, URL-encoded per
     * segment (the pipeline's url() regexes reject unencoded whitespace).
     *
     * @param string $file          Absolute file path.
     * @param string $kit_base_path Kit directory.
     * @return string
     */
    private static function relative_url($file, $kit_base_path) {
        $file = str_replace('\\', '/', $file);
        $base = rtrim(str_replace('\\', '/', $kit_base_path), '/');

        if ($base !== '' && strpos($file, $base . '/') === 0) {
            $relative = substr($file, strlen($base) + 1);
        } else {
            $relative = basename($file);
        }

        return implode('/', array_map('rawurlencode', explode('/', $relative)));
    }
}
